DATA_MAKE=$(shell date)

README.md: guessinggame.sh
        touch README.md
        echo "Project's title: Unix Workbench Project" > README.md
        echo $(DATA_MAKE) >> README.md
        wc -l guessinggame.sh | cut -f1 -d' ' >> README.md

clean: README.md
        rm README.md